//! Bundle the sound library (`sounds/`, #211): every `<id>.wav` there is
//! compiled in, and `sounds/defaults.txt` gives each event its default.
//! Generates `$OUT_DIR/sounds.rs` (see `earcon::library`).
use std::fmt::Write as _;
use std::path::PathBuf;

const EVENTS: &[&str] = &[
    "choice",
    "permission",
    "error",
    "turn_done",
    "nav",
    "nav_edge",
    "session_change",
    "summary_failed",
];

fn valid_id(id: &str) -> bool {
    !id.is_empty()
        && id.len() <= 40
        && id
            .chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-' || c == '_')
}

fn main() {
    let dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap()).join("sounds");
    println!("cargo:rerun-if-changed={}", dir.display());
    let mut ids: Vec<(String, PathBuf)> = std::fs::read_dir(&dir)
        .expect("crates/sonara-agent/sounds exists")
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|x| x.eq_ignore_ascii_case("wav")))
        .map(|p| {
            let id = p.file_stem().unwrap().to_string_lossy().to_string();
            assert!(
                valid_id(&id),
                "sounds/{id}.wav: a sound name is lowercase letters, digits, '-' or '_'"
            );
            println!("cargo:rerun-if-changed={}", p.display());
            (id, p)
        })
        .collect();
    ids.sort();
    let manifest = dir.join("defaults.txt");
    println!("cargo:rerun-if-changed={}", manifest.display());
    let text = std::fs::read_to_string(&manifest).expect("sounds/defaults.txt exists");
    let mut defaults = Vec::new();
    for (n, line) in text.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let (event, sound) = line
            .split_once('=')
            .unwrap_or_else(|| panic!("sounds/defaults.txt:{}: expected `event = sound`", n + 1));
        let (event, sound) = (event.trim(), sound.trim());
        assert!(
            EVENTS.contains(&event),
            "sounds/defaults.txt:{}: unknown event '{event}'",
            n + 1
        );
        assert!(
            sound == "none" || ids.iter().any(|(id, _)| id == sound),
            "sounds/defaults.txt:{}: no sounds/{sound}.wav",
            n + 1
        );
        if sound != "none" {
            defaults.push((event.to_string(), sound.to_string()));
        }
    }
    let mut out = String::new();
    out.push_str("/// The bundled sounds, by name (generated by build.rs).\n");
    out.push_str("pub(crate) const SOUNDS: &[(&str, &[u8])] = &[\n");
    for (id, path) in &ids {
        writeln!(
            out,
            "    ({id:?}, include_bytes!({:?})),",
            path.display().to_string()
        )
        .unwrap();
    }
    out.push_str("];\n\n/// Each event's default sound (events left out are silent).\n");
    out.push_str("pub(crate) const DEFAULTS: &[(&str, &str)] = &[\n");
    for (event, sound) in &defaults {
        writeln!(out, "    ({event:?}, {sound:?}),").unwrap();
    }
    out.push_str("];\n");
    let dest = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("sounds.rs");
    std::fs::write(dest, out).unwrap();
}
