"""Generate THIRD_PARTY_NOTICES.md (spec R6: the one obligation of a bundler
is to ship these notices).

Sources:
- ``cargo metadata``: every crate compiled into ``sonarad.exe`` for
  x86_64-pc-windows-msvc (normal dependencies only; build and dev
  dependencies do not ship), with its licence, authors and repository.
- ``models-and-data.md`` next to this script: hand-maintained notices for
  model weights, data and Microsoft components that are not crates.
- ``licenses/<SPDX id>.txt``: the full text of every licence in use.

The JS and Python clients have no dependencies, so they add nothing.

    python packaging/notices/gen_notices.py           # rewrite the file
    python packaging/notices/gen_notices.py --check   # exit 1 if it is stale (CI)

Stdlib only; needs ``cargo`` on PATH.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
OUT = REPO / "THIRD_PARTY_NOTICES.md"
TARGET = "x86_64-pc-windows-msvc"
ROOT_CRATE = "sonarad"
# Under an "A OR B" choice, the licence the notices elect (the simplest to
# comply with first). Every id here is also in deny.toml's allowlist.
PREFERENCE = ["MIT", "Apache-2.0", "BSD-3-Clause", "BSD-2-Clause", "ISC", "Zlib", "Unicode-3.0", "Unicode-DFS-2016"]


def cargo_metadata() -> dict:
    out = subprocess.run(
        ["cargo", "metadata", "--format-version", "1", "--locked", "--filter-platform", TARGET],
        cwd=REPO, capture_output=True, text=True, encoding="utf-8", check=True,
    )
    return json.loads(out.stdout)


def shipped_crates(meta: dict) -> list:
    """Third-party packages reachable from ROOT_CRATE through normal deps."""
    packages = {p["id"]: p for p in meta["packages"]}
    nodes = {n["id"]: n for n in meta["resolve"]["nodes"]}
    members = set(meta["workspace_members"])
    root = next(i for i in members if packages[i]["name"] == ROOT_CRATE)
    seen, stack = set(), [root]
    while stack:
        pid = stack.pop()
        if pid in seen:
            continue
        seen.add(pid)
        for dep in nodes[pid]["deps"]:
            if any(k["kind"] is None for k in dep["dep_kinds"]):
                stack.append(dep["pkg"])
    crates = [packages[i] for i in seen if i not in members]
    return sorted(crates, key=lambda p: (p["name"], p["version"]))


def _tokens(expr: str) -> list:
    return re.findall(r"\(|\)|[A-Za-z0-9.\-+]+(?: WITH [A-Za-z0-9.\-+]+)?", expr.replace("/", " OR "))


def elect(expr: str) -> list:
    """The licences the notices rely on for an SPDX expression: one choice
    per OR, all of an AND. ValueError when no choice is allowed."""
    toks = _tokens(expr)
    pos = 0

    def parse_or() -> list:
        nonlocal pos
        options = [parse_and()]
        while pos < len(toks) and toks[pos] == "OR":
            pos += 1
            options.append(parse_and())
        allowed = [o for o in options if all(x in PREFERENCE for x in o)]
        if not allowed:
            raise ValueError(f"no allowed licence in {expr!r}")
        return min(allowed, key=lambda o: [PREFERENCE.index(x) for x in o])

    def parse_and() -> list:
        nonlocal pos
        terms = parse_term()
        while pos < len(toks) and toks[pos] == "AND":
            pos += 1
            terms = terms + parse_term()
        return terms

    def parse_term() -> list:
        nonlocal pos
        tok = toks[pos]
        pos += 1
        if tok == "(":
            inner = parse_or()
            pos += 1  # ")"
            return inner
        return [tok]

    chosen = parse_or()
    return sorted(set(chosen), key=PREFERENCE.index)


def _authors(pkg: dict) -> str:
    names = [re.sub(r"\s*<[^>]*>", "", a).strip() for a in pkg.get("authors") or []]
    names = [n for n in names if n]
    return ", ".join(names) if names else f"the {pkg['name']} authors"


def render(crates: list) -> str:
    used = set()
    rows = []
    for p in crates:
        expr = p.get("license") or ""
        if not expr:
            raise SystemExit(f"{p['name']} {p['version']} declares no SPDX licence; add it to the notices by hand")
        chosen = elect(expr)
        used.update(chosen)
        repo = p.get("repository") or ""
        rows.append(f"| {p['name']} | {p['version']} | {expr} | {' AND '.join(chosen)} | {_authors(p)} | {repo} |")
    missing = sorted(x for x in used if not (HERE / "licenses" / f"{x}.txt").is_file())
    if missing:
        raise SystemExit(f"no licence text for {', '.join(missing)}: add packaging/notices/licenses/<id>.txt")

    parts = [
        "# Third-party notices",
        "",
        "<!-- Generated by packaging/notices/gen_notices.py from `cargo metadata` and"
        " packaging/notices/models-and-data.md. Do not edit by hand; CI checks it is current. -->",
        "",
        "Sonara is MIT-licensed (see `LICENSE`). Anyone may bundle it, sell their product, keep it"
        " closed-source, choose its licence and code-sign it; the one obligation is to ship this file"
        " with it (see `LICENSING.md`).",
        "",
        "The npm packages `@sonara/client` and `@sonara/runtime-win32-x64` and the Python package"
        " `sonara-client` have no third-party dependencies.",
        "",
        f"## Rust crates in sonarad.exe ({TARGET})",
        "",
        f"{len(crates)} crates. Where a crate offers a choice of licences, Sonara uses it under the one"
        " in the \"used under\" column. Copyright belongs to the authors listed.",
        "",
        "| crate | version | licence | used under | authors | source |",
        "|---|---|---|---|---|---|",
        *rows,
        "",
        (HERE / "models-and-data.md").read_text(encoding="utf-8").strip(),
        "",
        "## Licence texts",
        "",
    ]
    for lic in sorted(used, key=PREFERENCE.index):
        text = (HERE / "licenses" / f"{lic}.txt").read_text(encoding="utf-8").strip("\n")
        parts += [f"### {lic}", "", "```text", text, "```", ""]
    body = "\n".join(parts).rstrip("\n") + "\n"
    return body.replace("\r\n", "\n")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="exit 1 when THIRD_PARTY_NOTICES.md is out of date")
    args = ap.parse_args(argv)
    text = render(shipped_crates(cargo_metadata()))
    if args.check:
        current = OUT.read_text(encoding="utf-8").replace("\r\n", "\n") if OUT.is_file() else ""
        if current != text:
            print("THIRD_PARTY_NOTICES.md is out of date: run python packaging/notices/gen_notices.py",
                  file=sys.stderr)
            return 1
        print("THIRD_PARTY_NOTICES.md is up to date")
        return 0
    # open(newline=), not Path.write_text(newline=): that needs Python 3.10.
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"wrote {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
